name: Install Laravel SDK
on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: composer install
    - name: Install Laravel SDK
      run: composer require loov-payment/laravel-sdk

